### PR TITLE
Grafana 11 + Canvas

### PR DESCRIPTION
**Pull request by clementduveau**
Hello,

I am using this lab for demo purposes and I am currently switching it to Canvas.
It's probably a bit rough around the edges and I didn't change the README.

I don't expect you to merge it blindly, just know that it exists. I will change my main branch to fit my need but this one will stay steady. So if you ever want to take a look at Canvas, know that it's available.

Regards,

### CODE REVIEW

**Comment by clementduveau** [comment]
Also, I am not an expert in containerlab but is it expected to have such low bandwidth between containers ? I never got a chance to get anything turning even green in the dashboard.

**Comment by hellt** [comment]
Thanks @clementduveau 
it is great to see Canvas evolving 💪 

Unfortunately, Canvas still doesn't quite cut it for network engineering use case, since a tight integration with drawio is missing; placing the objects as a diagram overlay leads to unresponsive behavior, when changing the window size moves/resizes the panes, but Canvas elements stay the same (admittedly, I am not a Canvas expert and just used this branch to try things out)

Not sure what performance you referring to; the network nodes used in this lab though are limited with 1000pps, hence the link coloring used in the main branch goes from 0 to 5Mbps only

**Comment by clementduveau** [comment]
Canvas can _technically_ be used to create the diagrams but it's utterly painful compared to drawio. Hence why most people revert to just put elements on top of a static image (which I did too)

I might update it further in the future. You can close the PR, just know that this exists, and I will send another PR the day it gets better.

**Comment by hellt** [comment]
It looks like this one may be the succssor if the original author abandons the project https://github.com/andymchugh/andrewbmchugh-flow-panel

I will close this to keep the issue tracker clean.

**Pull request closed without merging**
